
package com.ecommerce.ws.requestsStatus;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getCustomerRequestStatus", targetNamespace = "http://xmlns.oracle.com/SelectCustomerRequest/SelectCustomerRequest/getCustomerRequestStatus")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetCustomerRequestStatus {


    /**
     * 
     * @param payload
     * @return
     *     returns com.ecommerce.ws.requestsStatus.RequestsCollection
     */
    @WebMethod(action = "process")
    @WebResult(name = "RequestsCollection", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/CustomerDB", partName = "payload")
    public RequestsCollection process(
        @WebParam(name = "CustomerDBSelect_CustIDInputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/CustomerDB", partName = "payload")
        CustomerDBSelectCustID payload);

}
