
package com.ecommerce.ws.certificateApproval;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApproveCertificate", targetNamespace = "http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApproveCertificate {


    /**
     * 
     * @param payload
     * @return
     *     returns com.ecommerce.ws.certificateApproval.ProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "processResponse", targetNamespace = "http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate", partName = "payload")
    public ProcessResponse process(
        @WebParam(name = "RequestsCollection", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/RequestsInsert", partName = "payload")
        RequestsCollection payload);

}
