
package com.ecommerce.ws.certificateApproval;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "approvecertificate_client_ep", targetNamespace = "http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate", wsdlLocation = "http://localhost:8001/soa-infra/services/default/CertificateV1/approvecertificate_client_ep?WSDL")
public class ApprovecertificateClientEp
    extends Service
{

    private final static URL APPROVECERTIFICATECLIENTEP_WSDL_LOCATION;
    private final static WebServiceException APPROVECERTIFICATECLIENTEP_EXCEPTION;
    private final static QName APPROVECERTIFICATECLIENTEP_QNAME = new QName("http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate", "approvecertificate_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/soa-infra/services/default/CertificateV1/approvecertificate_client_ep?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPROVECERTIFICATECLIENTEP_WSDL_LOCATION = url;
        APPROVECERTIFICATECLIENTEP_EXCEPTION = e;
    }

    public ApprovecertificateClientEp() {
        super(__getWsdlLocation(), APPROVECERTIFICATECLIENTEP_QNAME);
    }

    public ApprovecertificateClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPROVECERTIFICATECLIENTEP_QNAME, features);
    }

    public ApprovecertificateClientEp(URL wsdlLocation) {
        super(wsdlLocation, APPROVECERTIFICATECLIENTEP_QNAME);
    }

    public ApprovecertificateClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPROVECERTIFICATECLIENTEP_QNAME, features);
    }

    public ApprovecertificateClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApprovecertificateClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApproveCertificate
     */
    @WebEndpoint(name = "ApproveCertificate_pt")
    public ApproveCertificate getApproveCertificatePt() {
        return super.getPort(new QName("http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate", "ApproveCertificate_pt"), ApproveCertificate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApproveCertificate
     */
    @WebEndpoint(name = "ApproveCertificate_pt")
    public ApproveCertificate getApproveCertificatePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/CertificateApp/CertificateV1/ApproveCertificate", "ApproveCertificate_pt"), ApproveCertificate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPROVECERTIFICATECLIENTEP_EXCEPTION!= null) {
            throw APPROVECERTIFICATECLIENTEP_EXCEPTION;
        }
        return APPROVECERTIFICATECLIENTEP_WSDL_LOCATION;
    }

}
