
package com.ecommerce.ws.loanCalculators;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateLoanPortBindingQSService", targetNamespace = "http://loancalculation/", wsdlLocation = "http://localhost:7004/sbresource?Proxy/LoanSBProject%2FCalculateLoanPipelineProxyService")
public class CalculateLoanPortBindingQSService
    extends Service
{

    private final static URL CALCULATELOANPORTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATELOANPORTBINDINGQSSERVICE_EXCEPTION;
    private final static QName CALCULATELOANPORTBINDINGQSSERVICE_QNAME = new QName("http://loancalculation/", "CalculateLoanPortBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7004/sbresource?Proxy/LoanSBProject%2FCalculateLoanPipelineProxyService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATELOANPORTBINDINGQSSERVICE_WSDL_LOCATION = url;
        CALCULATELOANPORTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public CalculateLoanPortBindingQSService() {
        super(__getWsdlLocation(), CALCULATELOANPORTBINDINGQSSERVICE_QNAME);
    }

    public CalculateLoanPortBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATELOANPORTBINDINGQSSERVICE_QNAME, features);
    }

    public CalculateLoanPortBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATELOANPORTBINDINGQSSERVICE_QNAME);
    }

    public CalculateLoanPortBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATELOANPORTBINDINGQSSERVICE_QNAME, features);
    }

    public CalculateLoanPortBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateLoanPortBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateLoan
     */
    @WebEndpoint(name = "CalculateLoanPortBindingQSPort")
    public CalculateLoan getCalculateLoanPortBindingQSPort() {
        return super.getPort(new QName("http://loancalculation/", "CalculateLoanPortBindingQSPort"), CalculateLoan.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateLoan
     */
    @WebEndpoint(name = "CalculateLoanPortBindingQSPort")
    public CalculateLoan getCalculateLoanPortBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://loancalculation/", "CalculateLoanPortBindingQSPort"), CalculateLoan.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATELOANPORTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw CALCULATELOANPORTBINDINGQSSERVICE_EXCEPTION;
        }
        return CALCULATELOANPORTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
