
package com.ecommerce.ws.loanCalculators;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateLoanService", targetNamespace = "http://loancalculation/", wsdlLocation = "http://localhost:7004/sbresource?Proxy/LoanSBProject%2FProxyService")
public class CalculateLoanService
    extends Service
{

    private final static URL CALCULATELOANSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATELOANSERVICE_EXCEPTION;
    private final static QName CALCULATELOANSERVICE_QNAME = new QName("http://loancalculation/", "CalculateLoanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7004/sbresource?Proxy/LoanSBProject%2FProxyService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATELOANSERVICE_WSDL_LOCATION = url;
        CALCULATELOANSERVICE_EXCEPTION = e;
    }

    public CalculateLoanService() {
        super(__getWsdlLocation(), CALCULATELOANSERVICE_QNAME);
    }

    public CalculateLoanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATELOANSERVICE_QNAME, features);
    }

    public CalculateLoanService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATELOANSERVICE_QNAME);
    }

    public CalculateLoanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATELOANSERVICE_QNAME, features);
    }

    public CalculateLoanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateLoanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateLoan
     */
    @WebEndpoint(name = "CalculateLoanPort")
    public CalculateLoan getCalculateLoanPort() {
        return super.getPort(new QName("http://loancalculation/", "CalculateLoanPort"), CalculateLoan.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateLoan
     */
    @WebEndpoint(name = "CalculateLoanPort")
    public CalculateLoan getCalculateLoanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://loancalculation/", "CalculateLoanPort"), CalculateLoan.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATELOANSERVICE_EXCEPTION!= null) {
            throw CALCULATELOANSERVICE_EXCEPTION;
        }
        return CALCULATELOANSERVICE_WSDL_LOCATION;
    }

}
