
package com.ecommerce.ws.loanCalculators;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateLoan", targetNamespace = "http://loancalculation/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateLoan {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateLoan", targetNamespace = "http://loancalculation/", className = "com.ecommerce.ws.loanCalculators.CalculateLoan_Type")
    @ResponseWrapper(localName = "calculateLoanResponse", targetNamespace = "http://loancalculation/", className = "com.ecommerce.ws.loanCalculators.CalculateLoanResponse")
    public String calculateLoan(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
