
package com.ecommerce.ws.getAccounts;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerAccounts", targetNamespace = "http://xmlns.oracle.com/CertificateApp/CustomerAccounts/CustomerAccounts")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerAccounts {


    /**
     * 
     * @param payload
     * @return
     *     returns com.ecommerce.ws.getAccounts.AccountCollection
     */
    @WebMethod(action = "process")
    @WebResult(name = "AccountCollection", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/getAccounts", partName = "payload")
    public AccountCollection process(
        @WebParam(name = "getAccountsSelect_custIDInputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/top/getAccounts", partName = "payload")
        GetAccountsSelectCustID payload);

}
