
package com.ecommerce.ws.getAccounts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "customeraccounts_client_ep", targetNamespace = "http://xmlns.oracle.com/CertificateApp/CustomerAccounts/CustomerAccounts", wsdlLocation = "http://localhost:8001/soa-infra/services/default/CustomerAccounts/customeraccounts_client_ep?WSDL")
public class CustomeraccountsClientEp
    extends Service
{

    private final static URL CUSTOMERACCOUNTSCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERACCOUNTSCLIENTEP_EXCEPTION;
    private final static QName CUSTOMERACCOUNTSCLIENTEP_QNAME = new QName("http://xmlns.oracle.com/CertificateApp/CustomerAccounts/CustomerAccounts", "customeraccounts_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/soa-infra/services/default/CustomerAccounts/customeraccounts_client_ep?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERACCOUNTSCLIENTEP_WSDL_LOCATION = url;
        CUSTOMERACCOUNTSCLIENTEP_EXCEPTION = e;
    }

    public CustomeraccountsClientEp() {
        super(__getWsdlLocation(), CUSTOMERACCOUNTSCLIENTEP_QNAME);
    }

    public CustomeraccountsClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERACCOUNTSCLIENTEP_QNAME, features);
    }

    public CustomeraccountsClientEp(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERACCOUNTSCLIENTEP_QNAME);
    }

    public CustomeraccountsClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERACCOUNTSCLIENTEP_QNAME, features);
    }

    public CustomeraccountsClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomeraccountsClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerAccounts
     */
    @WebEndpoint(name = "CustomerAccounts_pt")
    public CustomerAccounts getCustomerAccountsPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/CertificateApp/CustomerAccounts/CustomerAccounts", "CustomerAccounts_pt"), CustomerAccounts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerAccounts
     */
    @WebEndpoint(name = "CustomerAccounts_pt")
    public CustomerAccounts getCustomerAccountsPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/CertificateApp/CustomerAccounts/CustomerAccounts", "CustomerAccounts_pt"), CustomerAccounts.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERACCOUNTSCLIENTEP_EXCEPTION!= null) {
            throw CUSTOMERACCOUNTSCLIENTEP_EXCEPTION;
        }
        return CUSTOMERACCOUNTSCLIENTEP_WSDL_LOCATION;
    }

}
